/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_FOCSTIM_RPC_CONSTANTS_PB_H_INCLUDED
#define PB_FOCSTIM_RPC_CONSTANTS_PB_H_INCLUDED
#include <pb.h>

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Enum definitions */
typedef enum _focstim_rpc_AxisType {
    focstim_rpc_AxisType_AXIS_UNKNOWN = 0,
    focstim_rpc_AxisType_AXIS_POSITION_ALPHA = 1, /* position parameters */
    focstim_rpc_AxisType_AXIS_POSITION_BETA = 2,
    focstim_rpc_AxisType_AXIS_POSITION_GAMMA = 3,
    /* AXIS_VOLUME_PERCENT = 10;    // not used */
    focstim_rpc_AxisType_AXIS_WAVEFORM_AMPLITUDE_AMPS = 11,
    focstim_rpc_AxisType_AXIS_CARRIER_FREQUENCY_HZ = 20, /* general pulse parameters */
    focstim_rpc_AxisType_AXIS_PULSE_WIDTH_IN_CYCLES = 21,
    focstim_rpc_AxisType_AXIS_PULSE_RISE_TIME_CYCLES = 22,
    focstim_rpc_AxisType_AXIS_PULSE_FREQUENCY_HZ = 23,
    focstim_rpc_AxisType_AXIS_PULSE_INTERVAL_RANDOM_PERCENT = 24,
    focstim_rpc_AxisType_AXIS_CALIBRATION_3_CENTER = 30,
    focstim_rpc_AxisType_AXIS_CALIBRATION_3_UP = 31,
    focstim_rpc_AxisType_AXIS_CALIBRATION_3_LEFT = 32,
    focstim_rpc_AxisType_AXIS_CALIBRATION_4_CENTER = 40, /* not used */
    focstim_rpc_AxisType_AXIS_CALIBRATION_4_A = 41,
    focstim_rpc_AxisType_AXIS_CALIBRATION_4_B = 42,
    focstim_rpc_AxisType_AXIS_CALIBRATION_4_C = 43,
    focstim_rpc_AxisType_AXIS_CALIBRATION_4_D = 44,
    focstim_rpc_AxisType_AXIS_CALIBRATION_4_REDUCTION_IN_CENTER = 45,
    focstim_rpc_AxisType_AXIS_ELECTRODE_1_POWER = 50,
    focstim_rpc_AxisType_AXIS_ELECTRODE_2_POWER = 51,
    focstim_rpc_AxisType_AXIS_ELECTRODE_3_POWER = 52,
    focstim_rpc_AxisType_AXIS_ELECTRODE_4_POWER = 53,
    /* --- stim-engine fork: OUTPUT_BIPHASIC_PAIRS (see firmware/NOTES.md) -------------------------------
 Two independent channels, A and B, each on an electrode pair (default A = 1-2, B = 3-4; live-routable,
 see *_ROUTE below). Each pulse is biphasic:
 leading phase, optional gap, return phase. Every setting is charge-balanced by construction: the
 return phase carries exactly the leading phase's charge (discrete sums equal, per pulse).
 All axes are read at the start of every pulse, so changes (including polarity) take effect on the
 next pulse without re-arming. Use MoveTo interval 0 for an instant switch. */
    focstim_rpc_AxisType_AXIS_BIPHASIC_A_AMPLITUDE_AMPS = 60, /* body current of the leading phase, 0..0.2 A (x device volume) */
    focstim_rpc_AxisType_AXIS_BIPHASIC_B_AMPLITUDE_AMPS = 61,
    focstim_rpc_AxisType_AXIS_BIPHASIC_A_PULSE_FREQUENCY_HZ = 62, /* 1..400 Hz, per pair (pairs run on independent clocks) */
    focstim_rpc_AxisType_AXIS_BIPHASIC_B_PULSE_FREQUENCY_HZ = 63,
    focstim_rpc_AxisType_AXIS_BIPHASIC_A_PHASE_WIDTH_US = 64, /* leading phase width, 40..400 us (20 us PWM steps) */
    focstim_rpc_AxisType_AXIS_BIPHASIC_B_PHASE_WIDTH_US = 65,
    focstim_rpc_AxisType_AXIS_BIPHASIC_INTERPHASE_GAP_US = 66, /* 0..200 us, both pairs */
    /* Leading polarity, live: flip it between pulses (MoveTo interval 0) for a blind lead-swap A/B.
 "Cathodic" is in the firmware's current sign convention; which physical terminal that is depends on
 transformer phasing and is confirmed on the bench (firmware/TEST-PLAN.md). */
    focstim_rpc_AxisType_AXIS_BIPHASIC_A_POLARITY = 67, /* < 0.5: the route's first electrode cathodic in the leading phase; >= 0.5: its second */
    focstim_rpc_AxisType_AXIS_BIPHASIC_B_POLARITY = 68, /* (default routes: A electrode 1 vs 2, B electrode 3 vs 4) */
    /* Phase asymmetry (ET-312-style unequal phases), live: return width = leading width x asymmetry, rounded to
 the 20 us grid (max 400 us x 4); the return amplitude is then set so its charge equals the leading phase's
 exactly (~ leading amplitude / asymmetry). 1 = symmetric. Net charge per pair is zero at every setting. */
    focstim_rpc_AxisType_AXIS_BIPHASIC_A_ASYMMETRY = 69, /* 1..4 */
    focstim_rpc_AxisType_AXIS_BIPHASIC_B_ASYMMETRY = 70,
    /* Live routing: which two electrodes each channel drives, as a two-digit code, first electrode then second
 (1-based): 12 = electrodes 1-2 (A default), 34 (B default), 23, 41, 13 ... any two different electrodes.
 Takes effect on the channel's next pulse, no re-arm. The TARGET value is used (MoveTo never glides through
 other routes); an invalid code is ignored. The polarity axis then picks which of the two leads: < 0.5 the
 first electrode of the code is cathodic. Both channels may share an electrode or the same pair: their
 pulses never overlap in time. A pair not driven for 1 s restarts its impedance estimate low (softer first
 pulses for a few pulses, never harder). */
    focstim_rpc_AxisType_AXIS_BIPHASIC_A_ROUTE = 71, /* 11..44 (12) */
    focstim_rpc_AxisType_AXIS_BIPHASIC_B_ROUTE = 72, /* 11..44 (34) */
    /* v2 (comment "stim-engine biphasic-pairs v2"): widths are fractional (no 20 us snapping; charge follows the
 width continuously) and the phase shape is selectable, live, per channel. The TARGET value is used, rounded.
 Amplitude stays = peak current. Unit-peak phase charge: rounded 2w/pi, square w, soft square w - edge. */
    focstim_rpc_AxisType_AXIS_BIPHASIC_A_SHAPE = 73, /* 0 rounded (half-sine, default), 1 square, 2 soft square (20 us edges) */
    focstim_rpc_AxisType_AXIS_BIPHASIC_B_SHAPE = 74
} focstim_rpc_AxisType;

typedef enum _focstim_rpc_BoardIdentifier {
    focstim_rpc_BoardIdentifier_BOARD_UNKNOWN = 0,
    focstim_rpc_BoardIdentifier_BOARD_B_G431B_ESC1 = 1, /* AKA 'V1' or 'V2' */
    focstim_rpc_BoardIdentifier_BOARD_FOCSTIM_V4 = 2 /* also V3 */
} focstim_rpc_BoardIdentifier;

typedef enum _focstim_rpc_OutputMode {
    focstim_rpc_OutputMode_OUTPUT_UNKNOWN = 0,
    /* OUTPUT_OFF = 1; */
    focstim_rpc_OutputMode_OUTPUT_THREEPHASE = 2,
    focstim_rpc_OutputMode_OUTPUT_FOURPHASE = 3, /* alpha, beta, gamma. DEPRECATED */
    focstim_rpc_OutputMode_OUTPUT_FOURPHASE_INDIVIDUAL_ELECTRODES = 4, /* e1/e2/e3/e4 */
    focstim_rpc_OutputMode_OUTPUT_BIPHASIC_PAIRS = 5 /* stim-engine fork: biphasic pulses on pairs 1-2 and 3-4 (AXIS_BIPHASIC_*) */
} focstim_rpc_OutputMode;

/* TODO: implement */
typedef enum _focstim_rpc_StreamingMode {
    focstim_rpc_StreamingMode_STREAMING_UNKNOWN = 0,
    focstim_rpc_StreamingMode_STREAMING_MOVETO = 1,
    focstim_rpc_StreamingMode_STREAMING_BUFFERED = 2
} focstim_rpc_StreamingMode;

typedef enum _focstim_rpc_Errors {
    focstim_rpc_Errors_ERROR_UNKNOWN = 0,
    focstim_rpc_Errors_ERROR_OUTPUT_NOT_SUPPORTED = 1,
    focstim_rpc_Errors_ERROR_UNKNOWN_REQUEST = 2,
    focstim_rpc_Errors_ERROR_POWER_NOT_PRESENT = 3,
    focstim_rpc_Errors_ERROR_ALREADY_PLAYING = 4
} focstim_rpc_Errors;

typedef enum _focstim_rpc_ButtonState {
    focstim_rpc_ButtonState_BUTTON_UNKNOWN = 0,
    focstim_rpc_ButtonState_BUTTON_DOWN = 1,
    focstim_rpc_ButtonState_BUTTON_UP = 2
} focstim_rpc_ButtonState;

#ifdef __cplusplus
extern "C" {
#endif

/* Helper constants for enums */
#define _focstim_rpc_AxisType_MIN focstim_rpc_AxisType_AXIS_UNKNOWN
#define _focstim_rpc_AxisType_MAX focstim_rpc_AxisType_AXIS_BIPHASIC_B_SHAPE
#define _focstim_rpc_AxisType_ARRAYSIZE ((focstim_rpc_AxisType)(focstim_rpc_AxisType_AXIS_BIPHASIC_B_SHAPE+1))

#define _focstim_rpc_BoardIdentifier_MIN focstim_rpc_BoardIdentifier_BOARD_UNKNOWN
#define _focstim_rpc_BoardIdentifier_MAX focstim_rpc_BoardIdentifier_BOARD_FOCSTIM_V4
#define _focstim_rpc_BoardIdentifier_ARRAYSIZE ((focstim_rpc_BoardIdentifier)(focstim_rpc_BoardIdentifier_BOARD_FOCSTIM_V4+1))

#define _focstim_rpc_OutputMode_MIN focstim_rpc_OutputMode_OUTPUT_UNKNOWN
#define _focstim_rpc_OutputMode_MAX focstim_rpc_OutputMode_OUTPUT_BIPHASIC_PAIRS
#define _focstim_rpc_OutputMode_ARRAYSIZE ((focstim_rpc_OutputMode)(focstim_rpc_OutputMode_OUTPUT_BIPHASIC_PAIRS+1))

#define _focstim_rpc_StreamingMode_MIN focstim_rpc_StreamingMode_STREAMING_UNKNOWN
#define _focstim_rpc_StreamingMode_MAX focstim_rpc_StreamingMode_STREAMING_BUFFERED
#define _focstim_rpc_StreamingMode_ARRAYSIZE ((focstim_rpc_StreamingMode)(focstim_rpc_StreamingMode_STREAMING_BUFFERED+1))

#define _focstim_rpc_Errors_MIN focstim_rpc_Errors_ERROR_UNKNOWN
#define _focstim_rpc_Errors_MAX focstim_rpc_Errors_ERROR_ALREADY_PLAYING
#define _focstim_rpc_Errors_ARRAYSIZE ((focstim_rpc_Errors)(focstim_rpc_Errors_ERROR_ALREADY_PLAYING+1))

#define _focstim_rpc_ButtonState_MIN focstim_rpc_ButtonState_BUTTON_UNKNOWN
#define _focstim_rpc_ButtonState_MAX focstim_rpc_ButtonState_BUTTON_UP
#define _focstim_rpc_ButtonState_ARRAYSIZE ((focstim_rpc_ButtonState)(focstim_rpc_ButtonState_BUTTON_UP+1))


#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
