/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "focstim_rpc.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(focstim_rpc_Notification, focstim_rpc_Notification, 2)


PB_BIND(focstim_rpc_Request, focstim_rpc_Request, 2)


PB_BIND(focstim_rpc_Response, focstim_rpc_Response, 2)


PB_BIND(focstim_rpc_Error, focstim_rpc_Error, AUTO)


PB_BIND(focstim_rpc_RpcMessage, focstim_rpc_RpcMessage, AUTO)



