/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_FOCSTIM_RPC_FOCSTIM_RPC_PB_H_INCLUDED
#define PB_FOCSTIM_RPC_FOCSTIM_RPC_PB_H_INCLUDED
#include <pb.h>
#include "notifications.pb.h"
#include "messages.pb.h"
#include "constants.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _focstim_rpc_Notification {
    pb_size_t which_notification;
    union {
        focstim_rpc_NotificationBoot notification_boot;
        focstim_rpc_NotificationDeviceVolume notification_device_volume;
        focstim_rpc_NotificationCurrents notification_currents;
        focstim_rpc_NotificationOutputResistance notification_output_resistance;
        focstim_rpc_NotificationSystemStats notification_system_stats;
        focstim_rpc_NotificationSignalStats notification_signal_stats;
        focstim_rpc_NotificationBattery notification_battery;
        focstim_rpc_NotificationLSM6DSOX notification_lsm6dsox;
        focstim_rpc_NotificationPressure notification_pressure;
        focstim_rpc_NotificationButtonPress notification_button_press;
        focstim_rpc_NotificationSkinResistance notification_skin_resistance;
        focstim_rpc_NotificationDebugString notification_debug_string;
        focstim_rpc_NotificationDebugAS5311 notification_debug_as5311;
        focstim_rpc_NotificationDebugEdging notification_debug_edging;
        focstim_rpc_NotificationDebugTeleplot notification_debug_teleplot;
    } notification;
    uint64_t timestamp;
} focstim_rpc_Notification;

typedef struct _focstim_rpc_Request {
    uint32_t id;
    pb_size_t which_params;
    union {
        /* MoveTo streaming API */
        focstim_rpc_RequestAxisMoveTo request_axis_move_to;
        /* general commands */
        focstim_rpc_RequestFirmwareVersion request_firmware_version;
        focstim_rpc_RequestCapabilitiesGet request_capabilities_get;
        focstim_rpc_RequestSignalStart request_signal_start;
        focstim_rpc_RequestSignalStop request_signal_stop;
        /* Buffered streaming API -- not yet implemented */
        focstim_rpc_RequestTimestampSet request_timestamp_set;
        focstim_rpc_RequestTimestampGet request_timestamp_get; /* RequestAxisSet request_axis_set = 506; */
        /* network */
        focstim_rpc_RequestWifiParametersSet request_wifi_parameters_set;
        focstim_rpc_RequestWifiIPGet request_wifi_ip_get;
        /* device volume lock */
        focstim_rpc_RequestLockDeviceVolume request_lock_device_volume;
        /* sensors */
        focstim_rpc_RequestLSM6DSOXStart request_lsm6dsox_start;
        focstim_rpc_RequestLSM6DSOXStop request_lsm6dsox_stop;
        /* debug */
        focstim_rpc_RequestDebugStm32DeepSleep request_debug_stm32_deep_sleep;
        focstim_rpc_RequestDebugEnterBootloader request_debug_enter_bootloader;
    } params;
} focstim_rpc_Request;

typedef struct _focstim_rpc_Error {
    focstim_rpc_Errors code; /* string message = 2;
 string data = 3; */
} focstim_rpc_Error;

/* Responses have the same ID as the request. NB! not all requests will have a result, and just return a blank response */
typedef struct _focstim_rpc_Response {
    uint32_t id;
    bool has_error;
    focstim_rpc_Error error; /* Transportation transport = 3; //optional - internal use only */
    pb_size_t which_result;
    union {
        /* MoveTo streaming API */
        focstim_rpc_ResponseAxisMoveTo response_axis_move_to;
        /* general commands */
        focstim_rpc_ResponseFirmwareVersion response_firmware_version;
        focstim_rpc_ResponseCapabilitiesGet response_capabilities_get;
        focstim_rpc_ResponseSignalStart response_signal_start;
        focstim_rpc_ResponseSignalStop response_signal_stop;
        /* Buffered streaming API -- not yet implemented */
        focstim_rpc_ResponseTimestampSet response_timestamp_set;
        focstim_rpc_ResponseTimestampGet response_timestamp_get; /* ResponseAxisSet response_axis_set = 506; */
        /* network */
        focstim_rpc_ResponseWifiParametersSet response_wifi_parameters_set;
        focstim_rpc_ResponseWifiIPGet response_wifi_ip_get;
        /* device volume lock */
        focstim_rpc_ResponseLockDeviceVolume response_lock_device_volume;
        /* sensors */
        focstim_rpc_ResponseLSM6DSOXStart response_lsm6dsox_start;
        focstim_rpc_ResponseLSM6DSOXStop response_lsm6dsox_stop;
        /* debug */
        focstim_rpc_ResponseDebugStm32DeepSleep response_debug_stm32_deep_sleep;
    } result;
} focstim_rpc_Response;

typedef struct _focstim_rpc_RpcMessage {
    pb_size_t which_message;
    union {
        focstim_rpc_Request request;
        /* Requests requests = 3; */
        focstim_rpc_Response response;
        focstim_rpc_Notification notification;
    } message;
} focstim_rpc_RpcMessage;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define focstim_rpc_Notification_init_default    {0, {focstim_rpc_NotificationBoot_init_default}, 0}
#define focstim_rpc_Request_init_default         {0, 0, {focstim_rpc_RequestAxisMoveTo_init_default}}
#define focstim_rpc_Response_init_default        {0, false, focstim_rpc_Error_init_default, 0, {focstim_rpc_ResponseAxisMoveTo_init_default}}
#define focstim_rpc_Error_init_default           {_focstim_rpc_Errors_MIN}
#define focstim_rpc_RpcMessage_init_default      {0, {focstim_rpc_Request_init_default}}
#define focstim_rpc_Notification_init_zero       {0, {focstim_rpc_NotificationBoot_init_zero}, 0}
#define focstim_rpc_Request_init_zero            {0, 0, {focstim_rpc_RequestAxisMoveTo_init_zero}}
#define focstim_rpc_Response_init_zero           {0, false, focstim_rpc_Error_init_zero, 0, {focstim_rpc_ResponseAxisMoveTo_init_zero}}
#define focstim_rpc_Error_init_zero              {_focstim_rpc_Errors_MIN}
#define focstim_rpc_RpcMessage_init_zero         {0, {focstim_rpc_Request_init_zero}}

/* Field tags (for use in manual encoding/decoding) */
#define focstim_rpc_Notification_notification_boot_tag 1
#define focstim_rpc_Notification_notification_device_volume_tag 2
#define focstim_rpc_Notification_notification_currents_tag 3
#define focstim_rpc_Notification_notification_output_resistance_tag 4
#define focstim_rpc_Notification_notification_system_stats_tag 5
#define focstim_rpc_Notification_notification_signal_stats_tag 6
#define focstim_rpc_Notification_notification_battery_tag 7
#define focstim_rpc_Notification_notification_lsm6dsox_tag 8
#define focstim_rpc_Notification_notification_pressure_tag 9
#define focstim_rpc_Notification_notification_button_press_tag 10
#define focstim_rpc_Notification_notification_skin_resistance_tag 11
#define focstim_rpc_Notification_notification_debug_string_tag 1000
#define focstim_rpc_Notification_notification_debug_as5311_tag 1001
#define focstim_rpc_Notification_notification_debug_edging_tag 1002
#define focstim_rpc_Notification_notification_debug_teleplot_tag 1003
#define focstim_rpc_Notification_timestamp_tag   999
#define focstim_rpc_Request_id_tag               1
#define focstim_rpc_Request_request_axis_move_to_tag 5
#define focstim_rpc_Request_request_firmware_version_tag 500
#define focstim_rpc_Request_request_capabilities_get_tag 501
#define focstim_rpc_Request_request_signal_start_tag 502
#define focstim_rpc_Request_request_signal_stop_tag 503
#define focstim_rpc_Request_request_timestamp_set_tag 504
#define focstim_rpc_Request_request_timestamp_get_tag 505
#define focstim_rpc_Request_request_wifi_parameters_set_tag 507
#define focstim_rpc_Request_request_wifi_ip_get_tag 508
#define focstim_rpc_Request_request_lock_device_volume_tag 509
#define focstim_rpc_Request_request_lsm6dsox_start_tag 600
#define focstim_rpc_Request_request_lsm6dsox_stop_tag 601
#define focstim_rpc_Request_request_debug_stm32_deep_sleep_tag 1000
#define focstim_rpc_Request_request_debug_enter_bootloader_tag 1001
#define focstim_rpc_Error_code_tag               1
#define focstim_rpc_Response_id_tag              1
#define focstim_rpc_Response_error_tag           3
#define focstim_rpc_Response_response_axis_move_to_tag 5
#define focstim_rpc_Response_response_firmware_version_tag 500
#define focstim_rpc_Response_response_capabilities_get_tag 501
#define focstim_rpc_Response_response_signal_start_tag 502
#define focstim_rpc_Response_response_signal_stop_tag 503
#define focstim_rpc_Response_response_timestamp_set_tag 504
#define focstim_rpc_Response_response_timestamp_get_tag 505
#define focstim_rpc_Response_response_wifi_parameters_set_tag 507
#define focstim_rpc_Response_response_wifi_ip_get_tag 508
#define focstim_rpc_Response_response_lock_device_volume_tag 509
#define focstim_rpc_Response_response_lsm6dsox_start_tag 600
#define focstim_rpc_Response_response_lsm6dsox_stop_tag 601
#define focstim_rpc_Response_response_debug_stm32_deep_sleep_tag 1000
#define focstim_rpc_RpcMessage_request_tag       2
#define focstim_rpc_RpcMessage_response_tag      4
#define focstim_rpc_RpcMessage_notification_tag  5

/* Struct field encoding specification for nanopb */
#define focstim_rpc_Notification_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (notification,notification_boot,notification.notification_boot),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (notification,notification_device_volume,notification.notification_device_volume),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (notification,notification_currents,notification.notification_currents),   3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (notification,notification_output_resistance,notification.notification_output_resistance),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (notification,notification_system_stats,notification.notification_system_stats),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (notification,notification_signal_stats,notification.notification_signal_stats),   6) \
X(a, STATIC,   ONEOF,    MESSAGE,  (notification,notification_battery,notification.notification_battery),   7) \
X(a, STATIC,   ONEOF,    MESSAGE,  (notification,notification_lsm6dsox,notification.notification_lsm6dsox),   8) \
X(a, STATIC,   ONEOF,    MESSAGE,  (notification,notification_pressure,notification.notification_pressure),   9) \
X(a, STATIC,   ONEOF,    MESSAGE,  (notification,notification_button_press,notification.notification_button_press),  10) \
X(a, STATIC,   ONEOF,    MESSAGE,  (notification,notification_skin_resistance,notification.notification_skin_resistance),  11) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp,       999) \
X(a, STATIC,   ONEOF,    MESSAGE,  (notification,notification_debug_string,notification.notification_debug_string), 1000) \
X(a, STATIC,   ONEOF,    MESSAGE,  (notification,notification_debug_as5311,notification.notification_debug_as5311), 1001) \
X(a, STATIC,   ONEOF,    MESSAGE,  (notification,notification_debug_edging,notification.notification_debug_edging), 1002) \
X(a, STATIC,   ONEOF,    MESSAGE,  (notification,notification_debug_teleplot,notification.notification_debug_teleplot), 1003)
#define focstim_rpc_Notification_CALLBACK NULL
#define focstim_rpc_Notification_DEFAULT NULL
#define focstim_rpc_Notification_notification_notification_boot_MSGTYPE focstim_rpc_NotificationBoot
#define focstim_rpc_Notification_notification_notification_device_volume_MSGTYPE focstim_rpc_NotificationDeviceVolume
#define focstim_rpc_Notification_notification_notification_currents_MSGTYPE focstim_rpc_NotificationCurrents
#define focstim_rpc_Notification_notification_notification_output_resistance_MSGTYPE focstim_rpc_NotificationOutputResistance
#define focstim_rpc_Notification_notification_notification_system_stats_MSGTYPE focstim_rpc_NotificationSystemStats
#define focstim_rpc_Notification_notification_notification_signal_stats_MSGTYPE focstim_rpc_NotificationSignalStats
#define focstim_rpc_Notification_notification_notification_battery_MSGTYPE focstim_rpc_NotificationBattery
#define focstim_rpc_Notification_notification_notification_lsm6dsox_MSGTYPE focstim_rpc_NotificationLSM6DSOX
#define focstim_rpc_Notification_notification_notification_pressure_MSGTYPE focstim_rpc_NotificationPressure
#define focstim_rpc_Notification_notification_notification_button_press_MSGTYPE focstim_rpc_NotificationButtonPress
#define focstim_rpc_Notification_notification_notification_skin_resistance_MSGTYPE focstim_rpc_NotificationSkinResistance
#define focstim_rpc_Notification_notification_notification_debug_string_MSGTYPE focstim_rpc_NotificationDebugString
#define focstim_rpc_Notification_notification_notification_debug_as5311_MSGTYPE focstim_rpc_NotificationDebugAS5311
#define focstim_rpc_Notification_notification_notification_debug_edging_MSGTYPE focstim_rpc_NotificationDebugEdging
#define focstim_rpc_Notification_notification_notification_debug_teleplot_MSGTYPE focstim_rpc_NotificationDebugTeleplot

#define focstim_rpc_Request_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,request_axis_move_to,params.request_axis_move_to),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,request_firmware_version,params.request_firmware_version), 500) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,request_capabilities_get,params.request_capabilities_get), 501) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,request_signal_start,params.request_signal_start), 502) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,request_signal_stop,params.request_signal_stop), 503) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,request_timestamp_set,params.request_timestamp_set), 504) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,request_timestamp_get,params.request_timestamp_get), 505) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,request_wifi_parameters_set,params.request_wifi_parameters_set), 507) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,request_wifi_ip_get,params.request_wifi_ip_get), 508) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,request_lock_device_volume,params.request_lock_device_volume), 509) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,request_lsm6dsox_start,params.request_lsm6dsox_start), 600) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,request_lsm6dsox_stop,params.request_lsm6dsox_stop), 601) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,request_debug_stm32_deep_sleep,params.request_debug_stm32_deep_sleep), 1000) \
X(a, STATIC,   ONEOF,    MESSAGE,  (params,request_debug_enter_bootloader,params.request_debug_enter_bootloader), 1001)
#define focstim_rpc_Request_CALLBACK NULL
#define focstim_rpc_Request_DEFAULT NULL
#define focstim_rpc_Request_params_request_axis_move_to_MSGTYPE focstim_rpc_RequestAxisMoveTo
#define focstim_rpc_Request_params_request_firmware_version_MSGTYPE focstim_rpc_RequestFirmwareVersion
#define focstim_rpc_Request_params_request_capabilities_get_MSGTYPE focstim_rpc_RequestCapabilitiesGet
#define focstim_rpc_Request_params_request_signal_start_MSGTYPE focstim_rpc_RequestSignalStart
#define focstim_rpc_Request_params_request_signal_stop_MSGTYPE focstim_rpc_RequestSignalStop
#define focstim_rpc_Request_params_request_timestamp_set_MSGTYPE focstim_rpc_RequestTimestampSet
#define focstim_rpc_Request_params_request_timestamp_get_MSGTYPE focstim_rpc_RequestTimestampGet
#define focstim_rpc_Request_params_request_wifi_parameters_set_MSGTYPE focstim_rpc_RequestWifiParametersSet
#define focstim_rpc_Request_params_request_wifi_ip_get_MSGTYPE focstim_rpc_RequestWifiIPGet
#define focstim_rpc_Request_params_request_lock_device_volume_MSGTYPE focstim_rpc_RequestLockDeviceVolume
#define focstim_rpc_Request_params_request_lsm6dsox_start_MSGTYPE focstim_rpc_RequestLSM6DSOXStart
#define focstim_rpc_Request_params_request_lsm6dsox_stop_MSGTYPE focstim_rpc_RequestLSM6DSOXStop
#define focstim_rpc_Request_params_request_debug_stm32_deep_sleep_MSGTYPE focstim_rpc_RequestDebugStm32DeepSleep
#define focstim_rpc_Request_params_request_debug_enter_bootloader_MSGTYPE focstim_rpc_RequestDebugEnterBootloader

#define focstim_rpc_Response_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   id,                1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  error,             3) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,response_axis_move_to,result.response_axis_move_to),   5) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,response_firmware_version,result.response_firmware_version), 500) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,response_capabilities_get,result.response_capabilities_get), 501) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,response_signal_start,result.response_signal_start), 502) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,response_signal_stop,result.response_signal_stop), 503) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,response_timestamp_set,result.response_timestamp_set), 504) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,response_timestamp_get,result.response_timestamp_get), 505) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,response_wifi_parameters_set,result.response_wifi_parameters_set), 507) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,response_wifi_ip_get,result.response_wifi_ip_get), 508) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,response_lock_device_volume,result.response_lock_device_volume), 509) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,response_lsm6dsox_start,result.response_lsm6dsox_start), 600) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,response_lsm6dsox_stop,result.response_lsm6dsox_stop), 601) \
X(a, STATIC,   ONEOF,    MESSAGE,  (result,response_debug_stm32_deep_sleep,result.response_debug_stm32_deep_sleep), 1000)
#define focstim_rpc_Response_CALLBACK NULL
#define focstim_rpc_Response_DEFAULT NULL
#define focstim_rpc_Response_error_MSGTYPE focstim_rpc_Error
#define focstim_rpc_Response_result_response_axis_move_to_MSGTYPE focstim_rpc_ResponseAxisMoveTo
#define focstim_rpc_Response_result_response_firmware_version_MSGTYPE focstim_rpc_ResponseFirmwareVersion
#define focstim_rpc_Response_result_response_capabilities_get_MSGTYPE focstim_rpc_ResponseCapabilitiesGet
#define focstim_rpc_Response_result_response_signal_start_MSGTYPE focstim_rpc_ResponseSignalStart
#define focstim_rpc_Response_result_response_signal_stop_MSGTYPE focstim_rpc_ResponseSignalStop
#define focstim_rpc_Response_result_response_timestamp_set_MSGTYPE focstim_rpc_ResponseTimestampSet
#define focstim_rpc_Response_result_response_timestamp_get_MSGTYPE focstim_rpc_ResponseTimestampGet
#define focstim_rpc_Response_result_response_wifi_parameters_set_MSGTYPE focstim_rpc_ResponseWifiParametersSet
#define focstim_rpc_Response_result_response_wifi_ip_get_MSGTYPE focstim_rpc_ResponseWifiIPGet
#define focstim_rpc_Response_result_response_lock_device_volume_MSGTYPE focstim_rpc_ResponseLockDeviceVolume
#define focstim_rpc_Response_result_response_lsm6dsox_start_MSGTYPE focstim_rpc_ResponseLSM6DSOXStart
#define focstim_rpc_Response_result_response_lsm6dsox_stop_MSGTYPE focstim_rpc_ResponseLSM6DSOXStop
#define focstim_rpc_Response_result_response_debug_stm32_deep_sleep_MSGTYPE focstim_rpc_ResponseDebugStm32DeepSleep

#define focstim_rpc_Error_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    code,              1)
#define focstim_rpc_Error_CALLBACK NULL
#define focstim_rpc_Error_DEFAULT NULL

#define focstim_rpc_RpcMessage_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,request,message.request),   2) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,response,message.response),   4) \
X(a, STATIC,   ONEOF,    MESSAGE,  (message,notification,message.notification),   5)
#define focstim_rpc_RpcMessage_CALLBACK NULL
#define focstim_rpc_RpcMessage_DEFAULT NULL
#define focstim_rpc_RpcMessage_message_request_MSGTYPE focstim_rpc_Request
#define focstim_rpc_RpcMessage_message_response_MSGTYPE focstim_rpc_Response
#define focstim_rpc_RpcMessage_message_notification_MSGTYPE focstim_rpc_Notification

extern const pb_msgdesc_t focstim_rpc_Notification_msg;
extern const pb_msgdesc_t focstim_rpc_Request_msg;
extern const pb_msgdesc_t focstim_rpc_Response_msg;
extern const pb_msgdesc_t focstim_rpc_Error_msg;
extern const pb_msgdesc_t focstim_rpc_RpcMessage_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define focstim_rpc_Notification_fields &focstim_rpc_Notification_msg
#define focstim_rpc_Request_fields &focstim_rpc_Request_msg
#define focstim_rpc_Response_fields &focstim_rpc_Response_msg
#define focstim_rpc_Error_fields &focstim_rpc_Error_msg
#define focstim_rpc_RpcMessage_fields &focstim_rpc_RpcMessage_msg

/* Maximum encoded size of messages (where known) */
#define FOCSTIM_RPC_FOCSTIM_RPC_PB_H_MAX_SIZE    focstim_rpc_RpcMessage_size
#define focstim_rpc_Error_size                   2
#define focstim_rpc_Notification_size            218
#define focstim_rpc_Request_size                 109
#define focstim_rpc_Response_size                125
#define focstim_rpc_RpcMessage_size              221

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
