/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_FOCSTIM_RPC_MESSAGES_PB_H_INCLUDED
#define PB_FOCSTIM_RPC_MESSAGES_PB_H_INCLUDED
#include <pb.h>
#include "constants.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _focstim_rpc_FirmwareVersion {
    uint32_t major;
    uint32_t minor;
    uint32_t revision;
    char branch[24];
    char comment[64];
} focstim_rpc_FirmwareVersion;

/* general commands */
typedef struct _focstim_rpc_RequestFirmwareVersion {
    char dummy_field;
} focstim_rpc_RequestFirmwareVersion;

typedef struct _focstim_rpc_ResponseFirmwareVersion {
    focstim_rpc_BoardIdentifier board; /* string stm32_firmware_version = 2;  // DEPRECATED */
    bool has_stm32_firmware_version_2;
    focstim_rpc_FirmwareVersion stm32_firmware_version_2; /* FirmwareVersion esp32_firmware = ???;  // TODO: implement */
} focstim_rpc_ResponseFirmwareVersion;

typedef struct _focstim_rpc_RequestCapabilitiesGet {
    char dummy_field;
} focstim_rpc_RequestCapabilitiesGet;

typedef struct _focstim_rpc_ResponseCapabilitiesGet {
    bool threephase;
    bool fourphase;
    bool battery; /* true if device has a battery installed */
    bool device_volume;
    float maximum_waveform_amplitude_amps;
    bool lsm6dsox;
} focstim_rpc_ResponseCapabilitiesGet;

typedef struct _focstim_rpc_RequestSignalStart {
    focstim_rpc_OutputMode mode; /* todo: max power? */
} focstim_rpc_RequestSignalStart;

typedef struct _focstim_rpc_ResponseSignalStart {
    char dummy_field;
} focstim_rpc_ResponseSignalStart;

typedef struct _focstim_rpc_RequestSignalStop {
    char dummy_field;
} focstim_rpc_RequestSignalStop;

typedef struct _focstim_rpc_ResponseSignalStop {
    char dummy_field;
} focstim_rpc_ResponseSignalStop;

/* TODO: implement? */
typedef struct _focstim_rpc_RequestModeSet {
    char dummy_field;
} focstim_rpc_RequestModeSet;

typedef struct _focstim_rpc_ResponseModeSet {
    char dummy_field;
} focstim_rpc_ResponseModeSet;

/* MoveTo streaming API */
typedef struct _focstim_rpc_RequestAxisMoveTo {
    focstim_rpc_AxisType axis;
    float value;
    uint32_t interval; /* in ms */
} focstim_rpc_RequestAxisMoveTo;

typedef struct _focstim_rpc_ResponseAxisMoveTo {
    char dummy_field;
} focstim_rpc_ResponseAxisMoveTo;

/* Buffered streaming API */
typedef struct _focstim_rpc_RequestAxisSet {
    focstim_rpc_AxisType axis;
    uint32_t timestamp_ms; /* unix timestamp, in ms, modulo 2^32 */
    float value; /*  */
    bool clear;
} focstim_rpc_RequestAxisSet;

typedef struct _focstim_rpc_ResponseAxisSet {
    char dummy_field;
} focstim_rpc_ResponseAxisSet;

/* Tell the system what unix timestamp is. Call regularly to avoid drift. */
typedef struct _focstim_rpc_RequestTimestampSet {
    uint64_t timestamp_ms; /* unix timestamp */
} focstim_rpc_RequestTimestampSet;

typedef struct _focstim_rpc_ResponseTimestampSet {
    int64_t offset_ms; /* new offset between epoch and local system clock */
    int64_t change_ms; /* how much the offset changed in the operation */
    int64_t error_ms; /* the error between */
} focstim_rpc_ResponseTimestampSet;

typedef struct _focstim_rpc_RequestTimestampGet {
    char dummy_field;
} focstim_rpc_RequestTimestampGet;

typedef struct _focstim_rpc_ResponseTimestampGet {
    uint32_t timestamp_ms; /* local clock, uint32_t on system. */
    uint64_t unix_timestamp_ms; /* synchronized clock */
} focstim_rpc_ResponseTimestampGet;

typedef PB_BYTES_ARRAY_T(32) focstim_rpc_RequestWifiParametersSet_ssid_t;
typedef PB_BYTES_ARRAY_T(64) focstim_rpc_RequestWifiParametersSet_password_t;
/* network */
typedef struct _focstim_rpc_RequestWifiParametersSet {
    focstim_rpc_RequestWifiParametersSet_ssid_t ssid;
    focstim_rpc_RequestWifiParametersSet_password_t password;
} focstim_rpc_RequestWifiParametersSet;

typedef struct _focstim_rpc_ResponseWifiParametersSet {
    char dummy_field;
} focstim_rpc_ResponseWifiParametersSet;

typedef struct _focstim_rpc_RequestWifiIPGet {
    char dummy_field;
} focstim_rpc_RequestWifiIPGet;

typedef struct _focstim_rpc_ResponseWifiIPGet {
    uint32_t ip;
} focstim_rpc_ResponseWifiIPGet;

typedef struct _focstim_rpc_RequestLockDeviceVolume {
    bool lock;
} focstim_rpc_RequestLockDeviceVolume;

typedef struct _focstim_rpc_ResponseLockDeviceVolume {
    char dummy_field;
} focstim_rpc_ResponseLockDeviceVolume;

/* sensors */
typedef struct _focstim_rpc_RequestLSM6DSOXStart {
    float imu_samplerate; /* Available values are 12.5, 26, 52, 104, 208, 417, 833, 1667, 3333, 6667 Hz */
    float acc_fullscale; /* Available values are: 2, 4, 8, 16 G */
    float gyr_fullscale; /* Available values are: 125, 250, 500, 1000, 2000 dps */
} focstim_rpc_RequestLSM6DSOXStart;

typedef struct _focstim_rpc_ResponseLSM6DSOXStart {
    float acc_sensitivity; /* conversion factor from readings to mili-g */
    float gyr_sensitivity; /* conversion factor from readings to mili-degrees-per-second */
} focstim_rpc_ResponseLSM6DSOXStart;

typedef struct _focstim_rpc_RequestLSM6DSOXStop {
    char dummy_field;
} focstim_rpc_RequestLSM6DSOXStop;

typedef struct _focstim_rpc_ResponseLSM6DSOXStop {
    char dummy_field;
} focstim_rpc_ResponseLSM6DSOXStop;

/* debug commands */
typedef struct _focstim_rpc_RequestDebugStm32DeepSleep {
    char dummy_field;
} focstim_rpc_RequestDebugStm32DeepSleep;

typedef struct _focstim_rpc_ResponseDebugStm32DeepSleep {
    char dummy_field;
} focstim_rpc_ResponseDebugStm32DeepSleep;

typedef struct _focstim_rpc_RequestDebugEnterBootloader {
    char dummy_field;
} focstim_rpc_RequestDebugEnterBootloader;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define focstim_rpc_FirmwareVersion_init_default {0, 0, 0, "", ""}
#define focstim_rpc_RequestFirmwareVersion_init_default {0}
#define focstim_rpc_ResponseFirmwareVersion_init_default {_focstim_rpc_BoardIdentifier_MIN, false, focstim_rpc_FirmwareVersion_init_default}
#define focstim_rpc_RequestCapabilitiesGet_init_default {0}
#define focstim_rpc_ResponseCapabilitiesGet_init_default {0, 0, 0, 0, 0, 0}
#define focstim_rpc_RequestSignalStart_init_default {_focstim_rpc_OutputMode_MIN}
#define focstim_rpc_ResponseSignalStart_init_default {0}
#define focstim_rpc_RequestSignalStop_init_default {0}
#define focstim_rpc_ResponseSignalStop_init_default {0}
#define focstim_rpc_RequestModeSet_init_default  {0}
#define focstim_rpc_ResponseModeSet_init_default {0}
#define focstim_rpc_RequestAxisMoveTo_init_default {_focstim_rpc_AxisType_MIN, 0, 0}
#define focstim_rpc_ResponseAxisMoveTo_init_default {0}
#define focstim_rpc_RequestAxisSet_init_default  {_focstim_rpc_AxisType_MIN, 0, 0, 0}
#define focstim_rpc_ResponseAxisSet_init_default {0}
#define focstim_rpc_RequestTimestampSet_init_default {0}
#define focstim_rpc_ResponseTimestampSet_init_default {0, 0, 0}
#define focstim_rpc_RequestTimestampGet_init_default {0}
#define focstim_rpc_ResponseTimestampGet_init_default {0, 0}
#define focstim_rpc_RequestWifiParametersSet_init_default {{0, {0}}, {0, {0}}}
#define focstim_rpc_ResponseWifiParametersSet_init_default {0}
#define focstim_rpc_RequestWifiIPGet_init_default {0}
#define focstim_rpc_ResponseWifiIPGet_init_default {0}
#define focstim_rpc_RequestLockDeviceVolume_init_default {0}
#define focstim_rpc_ResponseLockDeviceVolume_init_default {0}
#define focstim_rpc_RequestLSM6DSOXStart_init_default {0, 0, 0}
#define focstim_rpc_ResponseLSM6DSOXStart_init_default {0, 0}
#define focstim_rpc_RequestLSM6DSOXStop_init_default {0}
#define focstim_rpc_ResponseLSM6DSOXStop_init_default {0}
#define focstim_rpc_RequestDebugStm32DeepSleep_init_default {0}
#define focstim_rpc_ResponseDebugStm32DeepSleep_init_default {0}
#define focstim_rpc_RequestDebugEnterBootloader_init_default {0}
#define focstim_rpc_FirmwareVersion_init_zero    {0, 0, 0, "", ""}
#define focstim_rpc_RequestFirmwareVersion_init_zero {0}
#define focstim_rpc_ResponseFirmwareVersion_init_zero {_focstim_rpc_BoardIdentifier_MIN, false, focstim_rpc_FirmwareVersion_init_zero}
#define focstim_rpc_RequestCapabilitiesGet_init_zero {0}
#define focstim_rpc_ResponseCapabilitiesGet_init_zero {0, 0, 0, 0, 0, 0}
#define focstim_rpc_RequestSignalStart_init_zero {_focstim_rpc_OutputMode_MIN}
#define focstim_rpc_ResponseSignalStart_init_zero {0}
#define focstim_rpc_RequestSignalStop_init_zero  {0}
#define focstim_rpc_ResponseSignalStop_init_zero {0}
#define focstim_rpc_RequestModeSet_init_zero     {0}
#define focstim_rpc_ResponseModeSet_init_zero    {0}
#define focstim_rpc_RequestAxisMoveTo_init_zero  {_focstim_rpc_AxisType_MIN, 0, 0}
#define focstim_rpc_ResponseAxisMoveTo_init_zero {0}
#define focstim_rpc_RequestAxisSet_init_zero     {_focstim_rpc_AxisType_MIN, 0, 0, 0}
#define focstim_rpc_ResponseAxisSet_init_zero    {0}
#define focstim_rpc_RequestTimestampSet_init_zero {0}
#define focstim_rpc_ResponseTimestampSet_init_zero {0, 0, 0}
#define focstim_rpc_RequestTimestampGet_init_zero {0}
#define focstim_rpc_ResponseTimestampGet_init_zero {0, 0}
#define focstim_rpc_RequestWifiParametersSet_init_zero {{0, {0}}, {0, {0}}}
#define focstim_rpc_ResponseWifiParametersSet_init_zero {0}
#define focstim_rpc_RequestWifiIPGet_init_zero   {0}
#define focstim_rpc_ResponseWifiIPGet_init_zero  {0}
#define focstim_rpc_RequestLockDeviceVolume_init_zero {0}
#define focstim_rpc_ResponseLockDeviceVolume_init_zero {0}
#define focstim_rpc_RequestLSM6DSOXStart_init_zero {0, 0, 0}
#define focstim_rpc_ResponseLSM6DSOXStart_init_zero {0, 0}
#define focstim_rpc_RequestLSM6DSOXStop_init_zero {0}
#define focstim_rpc_ResponseLSM6DSOXStop_init_zero {0}
#define focstim_rpc_RequestDebugStm32DeepSleep_init_zero {0}
#define focstim_rpc_ResponseDebugStm32DeepSleep_init_zero {0}
#define focstim_rpc_RequestDebugEnterBootloader_init_zero {0}

/* Field tags (for use in manual encoding/decoding) */
#define focstim_rpc_FirmwareVersion_major_tag    1
#define focstim_rpc_FirmwareVersion_minor_tag    2
#define focstim_rpc_FirmwareVersion_revision_tag 3
#define focstim_rpc_FirmwareVersion_branch_tag   4
#define focstim_rpc_FirmwareVersion_comment_tag  5
#define focstim_rpc_ResponseFirmwareVersion_board_tag 1
#define focstim_rpc_ResponseFirmwareVersion_stm32_firmware_version_2_tag 3
#define focstim_rpc_ResponseCapabilitiesGet_threephase_tag 1
#define focstim_rpc_ResponseCapabilitiesGet_fourphase_tag 2
#define focstim_rpc_ResponseCapabilitiesGet_battery_tag 3
#define focstim_rpc_ResponseCapabilitiesGet_device_volume_tag 4
#define focstim_rpc_ResponseCapabilitiesGet_maximum_waveform_amplitude_amps_tag 5
#define focstim_rpc_ResponseCapabilitiesGet_lsm6dsox_tag 6
#define focstim_rpc_RequestSignalStart_mode_tag  1
#define focstim_rpc_RequestAxisMoveTo_axis_tag   1
#define focstim_rpc_RequestAxisMoveTo_value_tag  3
#define focstim_rpc_RequestAxisMoveTo_interval_tag 4
#define focstim_rpc_RequestAxisSet_axis_tag      1
#define focstim_rpc_RequestAxisSet_timestamp_ms_tag 2
#define focstim_rpc_RequestAxisSet_value_tag     3
#define focstim_rpc_RequestAxisSet_clear_tag     4
#define focstim_rpc_RequestTimestampSet_timestamp_ms_tag 1
#define focstim_rpc_ResponseTimestampSet_offset_ms_tag 1
#define focstim_rpc_ResponseTimestampSet_change_ms_tag 2
#define focstim_rpc_ResponseTimestampSet_error_ms_tag 3
#define focstim_rpc_ResponseTimestampGet_timestamp_ms_tag 1
#define focstim_rpc_ResponseTimestampGet_unix_timestamp_ms_tag 2
#define focstim_rpc_RequestWifiParametersSet_ssid_tag 1
#define focstim_rpc_RequestWifiParametersSet_password_tag 2
#define focstim_rpc_ResponseWifiIPGet_ip_tag     1
#define focstim_rpc_RequestLockDeviceVolume_lock_tag 1
#define focstim_rpc_RequestLSM6DSOXStart_imu_samplerate_tag 1
#define focstim_rpc_RequestLSM6DSOXStart_acc_fullscale_tag 2
#define focstim_rpc_RequestLSM6DSOXStart_gyr_fullscale_tag 3
#define focstim_rpc_ResponseLSM6DSOXStart_acc_sensitivity_tag 1
#define focstim_rpc_ResponseLSM6DSOXStart_gyr_sensitivity_tag 2

/* Struct field encoding specification for nanopb */
#define focstim_rpc_FirmwareVersion_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   major,             1) \
X(a, STATIC,   SINGULAR, UINT32,   minor,             2) \
X(a, STATIC,   SINGULAR, UINT32,   revision,          3) \
X(a, STATIC,   SINGULAR, STRING,   branch,            4) \
X(a, STATIC,   SINGULAR, STRING,   comment,           5)
#define focstim_rpc_FirmwareVersion_CALLBACK NULL
#define focstim_rpc_FirmwareVersion_DEFAULT NULL

#define focstim_rpc_RequestFirmwareVersion_FIELDLIST(X, a) \

#define focstim_rpc_RequestFirmwareVersion_CALLBACK NULL
#define focstim_rpc_RequestFirmwareVersion_DEFAULT NULL

#define focstim_rpc_ResponseFirmwareVersion_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    board,             1) \
X(a, STATIC,   OPTIONAL, MESSAGE,  stm32_firmware_version_2,   3)
#define focstim_rpc_ResponseFirmwareVersion_CALLBACK NULL
#define focstim_rpc_ResponseFirmwareVersion_DEFAULT NULL
#define focstim_rpc_ResponseFirmwareVersion_stm32_firmware_version_2_MSGTYPE focstim_rpc_FirmwareVersion

#define focstim_rpc_RequestCapabilitiesGet_FIELDLIST(X, a) \

#define focstim_rpc_RequestCapabilitiesGet_CALLBACK NULL
#define focstim_rpc_RequestCapabilitiesGet_DEFAULT NULL

#define focstim_rpc_ResponseCapabilitiesGet_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     threephase,        1) \
X(a, STATIC,   SINGULAR, BOOL,     fourphase,         2) \
X(a, STATIC,   SINGULAR, BOOL,     battery,           3) \
X(a, STATIC,   SINGULAR, BOOL,     device_volume,     4) \
X(a, STATIC,   SINGULAR, FLOAT,    maximum_waveform_amplitude_amps,   5) \
X(a, STATIC,   SINGULAR, BOOL,     lsm6dsox,          6)
#define focstim_rpc_ResponseCapabilitiesGet_CALLBACK NULL
#define focstim_rpc_ResponseCapabilitiesGet_DEFAULT NULL

#define focstim_rpc_RequestSignalStart_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    mode,              1)
#define focstim_rpc_RequestSignalStart_CALLBACK NULL
#define focstim_rpc_RequestSignalStart_DEFAULT NULL

#define focstim_rpc_ResponseSignalStart_FIELDLIST(X, a) \

#define focstim_rpc_ResponseSignalStart_CALLBACK NULL
#define focstim_rpc_ResponseSignalStart_DEFAULT NULL

#define focstim_rpc_RequestSignalStop_FIELDLIST(X, a) \

#define focstim_rpc_RequestSignalStop_CALLBACK NULL
#define focstim_rpc_RequestSignalStop_DEFAULT NULL

#define focstim_rpc_ResponseSignalStop_FIELDLIST(X, a) \

#define focstim_rpc_ResponseSignalStop_CALLBACK NULL
#define focstim_rpc_ResponseSignalStop_DEFAULT NULL

#define focstim_rpc_RequestModeSet_FIELDLIST(X, a) \

#define focstim_rpc_RequestModeSet_CALLBACK NULL
#define focstim_rpc_RequestModeSet_DEFAULT NULL

#define focstim_rpc_ResponseModeSet_FIELDLIST(X, a) \

#define focstim_rpc_ResponseModeSet_CALLBACK NULL
#define focstim_rpc_ResponseModeSet_DEFAULT NULL

#define focstim_rpc_RequestAxisMoveTo_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    axis,              1) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             3) \
X(a, STATIC,   SINGULAR, UINT32,   interval,          4)
#define focstim_rpc_RequestAxisMoveTo_CALLBACK NULL
#define focstim_rpc_RequestAxisMoveTo_DEFAULT NULL

#define focstim_rpc_ResponseAxisMoveTo_FIELDLIST(X, a) \

#define focstim_rpc_ResponseAxisMoveTo_CALLBACK NULL
#define focstim_rpc_ResponseAxisMoveTo_DEFAULT NULL

#define focstim_rpc_RequestAxisSet_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    axis,              1) \
X(a, STATIC,   SINGULAR, FIXED32,  timestamp_ms,      2) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             3) \
X(a, STATIC,   SINGULAR, BOOL,     clear,             4)
#define focstim_rpc_RequestAxisSet_CALLBACK NULL
#define focstim_rpc_RequestAxisSet_DEFAULT NULL

#define focstim_rpc_ResponseAxisSet_FIELDLIST(X, a) \

#define focstim_rpc_ResponseAxisSet_CALLBACK NULL
#define focstim_rpc_ResponseAxisSet_DEFAULT NULL

#define focstim_rpc_RequestTimestampSet_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT64,   timestamp_ms,      1)
#define focstim_rpc_RequestTimestampSet_CALLBACK NULL
#define focstim_rpc_RequestTimestampSet_DEFAULT NULL

#define focstim_rpc_ResponseTimestampSet_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT64,    offset_ms,         1) \
X(a, STATIC,   SINGULAR, SINT64,   change_ms,         2) \
X(a, STATIC,   SINGULAR, SINT64,   error_ms,          3)
#define focstim_rpc_ResponseTimestampSet_CALLBACK NULL
#define focstim_rpc_ResponseTimestampSet_DEFAULT NULL

#define focstim_rpc_RequestTimestampGet_FIELDLIST(X, a) \

#define focstim_rpc_RequestTimestampGet_CALLBACK NULL
#define focstim_rpc_RequestTimestampGet_DEFAULT NULL

#define focstim_rpc_ResponseTimestampGet_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FIXED32,  timestamp_ms,      1) \
X(a, STATIC,   SINGULAR, UINT64,   unix_timestamp_ms,   2)
#define focstim_rpc_ResponseTimestampGet_CALLBACK NULL
#define focstim_rpc_ResponseTimestampGet_DEFAULT NULL

#define focstim_rpc_RequestWifiParametersSet_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BYTES,    ssid,              1) \
X(a, STATIC,   SINGULAR, BYTES,    password,          2)
#define focstim_rpc_RequestWifiParametersSet_CALLBACK NULL
#define focstim_rpc_RequestWifiParametersSet_DEFAULT NULL

#define focstim_rpc_ResponseWifiParametersSet_FIELDLIST(X, a) \

#define focstim_rpc_ResponseWifiParametersSet_CALLBACK NULL
#define focstim_rpc_ResponseWifiParametersSet_DEFAULT NULL

#define focstim_rpc_RequestWifiIPGet_FIELDLIST(X, a) \

#define focstim_rpc_RequestWifiIPGet_CALLBACK NULL
#define focstim_rpc_RequestWifiIPGet_DEFAULT NULL

#define focstim_rpc_ResponseWifiIPGet_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UINT32,   ip,                1)
#define focstim_rpc_ResponseWifiIPGet_CALLBACK NULL
#define focstim_rpc_ResponseWifiIPGet_DEFAULT NULL

#define focstim_rpc_RequestLockDeviceVolume_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, BOOL,     lock,              1)
#define focstim_rpc_RequestLockDeviceVolume_CALLBACK NULL
#define focstim_rpc_RequestLockDeviceVolume_DEFAULT NULL

#define focstim_rpc_ResponseLockDeviceVolume_FIELDLIST(X, a) \

#define focstim_rpc_ResponseLockDeviceVolume_CALLBACK NULL
#define focstim_rpc_ResponseLockDeviceVolume_DEFAULT NULL

#define focstim_rpc_RequestLSM6DSOXStart_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    imu_samplerate,    1) \
X(a, STATIC,   SINGULAR, FLOAT,    acc_fullscale,     2) \
X(a, STATIC,   SINGULAR, FLOAT,    gyr_fullscale,     3)
#define focstim_rpc_RequestLSM6DSOXStart_CALLBACK NULL
#define focstim_rpc_RequestLSM6DSOXStart_DEFAULT NULL

#define focstim_rpc_ResponseLSM6DSOXStart_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    acc_sensitivity,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    gyr_sensitivity,   2)
#define focstim_rpc_ResponseLSM6DSOXStart_CALLBACK NULL
#define focstim_rpc_ResponseLSM6DSOXStart_DEFAULT NULL

#define focstim_rpc_RequestLSM6DSOXStop_FIELDLIST(X, a) \

#define focstim_rpc_RequestLSM6DSOXStop_CALLBACK NULL
#define focstim_rpc_RequestLSM6DSOXStop_DEFAULT NULL

#define focstim_rpc_ResponseLSM6DSOXStop_FIELDLIST(X, a) \

#define focstim_rpc_ResponseLSM6DSOXStop_CALLBACK NULL
#define focstim_rpc_ResponseLSM6DSOXStop_DEFAULT NULL

#define focstim_rpc_RequestDebugStm32DeepSleep_FIELDLIST(X, a) \

#define focstim_rpc_RequestDebugStm32DeepSleep_CALLBACK NULL
#define focstim_rpc_RequestDebugStm32DeepSleep_DEFAULT NULL

#define focstim_rpc_ResponseDebugStm32DeepSleep_FIELDLIST(X, a) \

#define focstim_rpc_ResponseDebugStm32DeepSleep_CALLBACK NULL
#define focstim_rpc_ResponseDebugStm32DeepSleep_DEFAULT NULL

#define focstim_rpc_RequestDebugEnterBootloader_FIELDLIST(X, a) \

#define focstim_rpc_RequestDebugEnterBootloader_CALLBACK NULL
#define focstim_rpc_RequestDebugEnterBootloader_DEFAULT NULL

extern const pb_msgdesc_t focstim_rpc_FirmwareVersion_msg;
extern const pb_msgdesc_t focstim_rpc_RequestFirmwareVersion_msg;
extern const pb_msgdesc_t focstim_rpc_ResponseFirmwareVersion_msg;
extern const pb_msgdesc_t focstim_rpc_RequestCapabilitiesGet_msg;
extern const pb_msgdesc_t focstim_rpc_ResponseCapabilitiesGet_msg;
extern const pb_msgdesc_t focstim_rpc_RequestSignalStart_msg;
extern const pb_msgdesc_t focstim_rpc_ResponseSignalStart_msg;
extern const pb_msgdesc_t focstim_rpc_RequestSignalStop_msg;
extern const pb_msgdesc_t focstim_rpc_ResponseSignalStop_msg;
extern const pb_msgdesc_t focstim_rpc_RequestModeSet_msg;
extern const pb_msgdesc_t focstim_rpc_ResponseModeSet_msg;
extern const pb_msgdesc_t focstim_rpc_RequestAxisMoveTo_msg;
extern const pb_msgdesc_t focstim_rpc_ResponseAxisMoveTo_msg;
extern const pb_msgdesc_t focstim_rpc_RequestAxisSet_msg;
extern const pb_msgdesc_t focstim_rpc_ResponseAxisSet_msg;
extern const pb_msgdesc_t focstim_rpc_RequestTimestampSet_msg;
extern const pb_msgdesc_t focstim_rpc_ResponseTimestampSet_msg;
extern const pb_msgdesc_t focstim_rpc_RequestTimestampGet_msg;
extern const pb_msgdesc_t focstim_rpc_ResponseTimestampGet_msg;
extern const pb_msgdesc_t focstim_rpc_RequestWifiParametersSet_msg;
extern const pb_msgdesc_t focstim_rpc_ResponseWifiParametersSet_msg;
extern const pb_msgdesc_t focstim_rpc_RequestWifiIPGet_msg;
extern const pb_msgdesc_t focstim_rpc_ResponseWifiIPGet_msg;
extern const pb_msgdesc_t focstim_rpc_RequestLockDeviceVolume_msg;
extern const pb_msgdesc_t focstim_rpc_ResponseLockDeviceVolume_msg;
extern const pb_msgdesc_t focstim_rpc_RequestLSM6DSOXStart_msg;
extern const pb_msgdesc_t focstim_rpc_ResponseLSM6DSOXStart_msg;
extern const pb_msgdesc_t focstim_rpc_RequestLSM6DSOXStop_msg;
extern const pb_msgdesc_t focstim_rpc_ResponseLSM6DSOXStop_msg;
extern const pb_msgdesc_t focstim_rpc_RequestDebugStm32DeepSleep_msg;
extern const pb_msgdesc_t focstim_rpc_ResponseDebugStm32DeepSleep_msg;
extern const pb_msgdesc_t focstim_rpc_RequestDebugEnterBootloader_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define focstim_rpc_FirmwareVersion_fields &focstim_rpc_FirmwareVersion_msg
#define focstim_rpc_RequestFirmwareVersion_fields &focstim_rpc_RequestFirmwareVersion_msg
#define focstim_rpc_ResponseFirmwareVersion_fields &focstim_rpc_ResponseFirmwareVersion_msg
#define focstim_rpc_RequestCapabilitiesGet_fields &focstim_rpc_RequestCapabilitiesGet_msg
#define focstim_rpc_ResponseCapabilitiesGet_fields &focstim_rpc_ResponseCapabilitiesGet_msg
#define focstim_rpc_RequestSignalStart_fields &focstim_rpc_RequestSignalStart_msg
#define focstim_rpc_ResponseSignalStart_fields &focstim_rpc_ResponseSignalStart_msg
#define focstim_rpc_RequestSignalStop_fields &focstim_rpc_RequestSignalStop_msg
#define focstim_rpc_ResponseSignalStop_fields &focstim_rpc_ResponseSignalStop_msg
#define focstim_rpc_RequestModeSet_fields &focstim_rpc_RequestModeSet_msg
#define focstim_rpc_ResponseModeSet_fields &focstim_rpc_ResponseModeSet_msg
#define focstim_rpc_RequestAxisMoveTo_fields &focstim_rpc_RequestAxisMoveTo_msg
#define focstim_rpc_ResponseAxisMoveTo_fields &focstim_rpc_ResponseAxisMoveTo_msg
#define focstim_rpc_RequestAxisSet_fields &focstim_rpc_RequestAxisSet_msg
#define focstim_rpc_ResponseAxisSet_fields &focstim_rpc_ResponseAxisSet_msg
#define focstim_rpc_RequestTimestampSet_fields &focstim_rpc_RequestTimestampSet_msg
#define focstim_rpc_ResponseTimestampSet_fields &focstim_rpc_ResponseTimestampSet_msg
#define focstim_rpc_RequestTimestampGet_fields &focstim_rpc_RequestTimestampGet_msg
#define focstim_rpc_ResponseTimestampGet_fields &focstim_rpc_ResponseTimestampGet_msg
#define focstim_rpc_RequestWifiParametersSet_fields &focstim_rpc_RequestWifiParametersSet_msg
#define focstim_rpc_ResponseWifiParametersSet_fields &focstim_rpc_ResponseWifiParametersSet_msg
#define focstim_rpc_RequestWifiIPGet_fields &focstim_rpc_RequestWifiIPGet_msg
#define focstim_rpc_ResponseWifiIPGet_fields &focstim_rpc_ResponseWifiIPGet_msg
#define focstim_rpc_RequestLockDeviceVolume_fields &focstim_rpc_RequestLockDeviceVolume_msg
#define focstim_rpc_ResponseLockDeviceVolume_fields &focstim_rpc_ResponseLockDeviceVolume_msg
#define focstim_rpc_RequestLSM6DSOXStart_fields &focstim_rpc_RequestLSM6DSOXStart_msg
#define focstim_rpc_ResponseLSM6DSOXStart_fields &focstim_rpc_ResponseLSM6DSOXStart_msg
#define focstim_rpc_RequestLSM6DSOXStop_fields &focstim_rpc_RequestLSM6DSOXStop_msg
#define focstim_rpc_ResponseLSM6DSOXStop_fields &focstim_rpc_ResponseLSM6DSOXStop_msg
#define focstim_rpc_RequestDebugStm32DeepSleep_fields &focstim_rpc_RequestDebugStm32DeepSleep_msg
#define focstim_rpc_ResponseDebugStm32DeepSleep_fields &focstim_rpc_ResponseDebugStm32DeepSleep_msg
#define focstim_rpc_RequestDebugEnterBootloader_fields &focstim_rpc_RequestDebugEnterBootloader_msg

/* Maximum encoded size of messages (where known) */
#define FOCSTIM_RPC_MESSAGES_PB_H_MAX_SIZE       focstim_rpc_ResponseFirmwareVersion_size
#define focstim_rpc_FirmwareVersion_size         108
#define focstim_rpc_RequestAxisMoveTo_size       13
#define focstim_rpc_RequestAxisSet_size          14
#define focstim_rpc_RequestCapabilitiesGet_size  0
#define focstim_rpc_RequestDebugEnterBootloader_size 0
#define focstim_rpc_RequestDebugStm32DeepSleep_size 0
#define focstim_rpc_RequestFirmwareVersion_size  0
#define focstim_rpc_RequestLSM6DSOXStart_size    15
#define focstim_rpc_RequestLSM6DSOXStop_size     0
#define focstim_rpc_RequestLockDeviceVolume_size 2
#define focstim_rpc_RequestModeSet_size          0
#define focstim_rpc_RequestSignalStart_size      2
#define focstim_rpc_RequestSignalStop_size       0
#define focstim_rpc_RequestTimestampGet_size     0
#define focstim_rpc_RequestTimestampSet_size     11
#define focstim_rpc_RequestWifiIPGet_size        0
#define focstim_rpc_RequestWifiParametersSet_size 100
#define focstim_rpc_ResponseAxisMoveTo_size      0
#define focstim_rpc_ResponseAxisSet_size         0
#define focstim_rpc_ResponseCapabilitiesGet_size 15
#define focstim_rpc_ResponseDebugStm32DeepSleep_size 0
#define focstim_rpc_ResponseFirmwareVersion_size 112
#define focstim_rpc_ResponseLSM6DSOXStart_size   10
#define focstim_rpc_ResponseLSM6DSOXStop_size    0
#define focstim_rpc_ResponseLockDeviceVolume_size 0
#define focstim_rpc_ResponseModeSet_size         0
#define focstim_rpc_ResponseSignalStart_size     0
#define focstim_rpc_ResponseSignalStop_size      0
#define focstim_rpc_ResponseTimestampGet_size    16
#define focstim_rpc_ResponseTimestampSet_size    33
#define focstim_rpc_ResponseWifiIPGet_size       6
#define focstim_rpc_ResponseWifiParametersSet_size 0

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
