/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "messages.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(focstim_rpc_FirmwareVersion, focstim_rpc_FirmwareVersion, AUTO)


PB_BIND(focstim_rpc_RequestFirmwareVersion, focstim_rpc_RequestFirmwareVersion, AUTO)


PB_BIND(focstim_rpc_ResponseFirmwareVersion, focstim_rpc_ResponseFirmwareVersion, AUTO)


PB_BIND(focstim_rpc_RequestCapabilitiesGet, focstim_rpc_RequestCapabilitiesGet, AUTO)


PB_BIND(focstim_rpc_ResponseCapabilitiesGet, focstim_rpc_ResponseCapabilitiesGet, AUTO)


PB_BIND(focstim_rpc_RequestSignalStart, focstim_rpc_RequestSignalStart, AUTO)


PB_BIND(focstim_rpc_ResponseSignalStart, focstim_rpc_ResponseSignalStart, AUTO)


PB_BIND(focstim_rpc_RequestSignalStop, focstim_rpc_RequestSignalStop, AUTO)


PB_BIND(focstim_rpc_ResponseSignalStop, focstim_rpc_ResponseSignalStop, AUTO)


PB_BIND(focstim_rpc_RequestModeSet, focstim_rpc_RequestModeSet, AUTO)


PB_BIND(focstim_rpc_ResponseModeSet, focstim_rpc_ResponseModeSet, AUTO)


PB_BIND(focstim_rpc_RequestAxisMoveTo, focstim_rpc_RequestAxisMoveTo, AUTO)


PB_BIND(focstim_rpc_ResponseAxisMoveTo, focstim_rpc_ResponseAxisMoveTo, AUTO)


PB_BIND(focstim_rpc_RequestAxisSet, focstim_rpc_RequestAxisSet, AUTO)


PB_BIND(focstim_rpc_ResponseAxisSet, focstim_rpc_ResponseAxisSet, AUTO)


PB_BIND(focstim_rpc_RequestTimestampSet, focstim_rpc_RequestTimestampSet, AUTO)


PB_BIND(focstim_rpc_ResponseTimestampSet, focstim_rpc_ResponseTimestampSet, AUTO)


PB_BIND(focstim_rpc_RequestTimestampGet, focstim_rpc_RequestTimestampGet, AUTO)


PB_BIND(focstim_rpc_ResponseTimestampGet, focstim_rpc_ResponseTimestampGet, AUTO)


PB_BIND(focstim_rpc_RequestWifiParametersSet, focstim_rpc_RequestWifiParametersSet, AUTO)


PB_BIND(focstim_rpc_ResponseWifiParametersSet, focstim_rpc_ResponseWifiParametersSet, AUTO)


PB_BIND(focstim_rpc_RequestWifiIPGet, focstim_rpc_RequestWifiIPGet, AUTO)


PB_BIND(focstim_rpc_ResponseWifiIPGet, focstim_rpc_ResponseWifiIPGet, AUTO)


PB_BIND(focstim_rpc_RequestLockDeviceVolume, focstim_rpc_RequestLockDeviceVolume, AUTO)


PB_BIND(focstim_rpc_ResponseLockDeviceVolume, focstim_rpc_ResponseLockDeviceVolume, AUTO)


PB_BIND(focstim_rpc_RequestLSM6DSOXStart, focstim_rpc_RequestLSM6DSOXStart, AUTO)


PB_BIND(focstim_rpc_ResponseLSM6DSOXStart, focstim_rpc_ResponseLSM6DSOXStart, AUTO)


PB_BIND(focstim_rpc_RequestLSM6DSOXStop, focstim_rpc_RequestLSM6DSOXStop, AUTO)


PB_BIND(focstim_rpc_ResponseLSM6DSOXStop, focstim_rpc_ResponseLSM6DSOXStop, AUTO)


PB_BIND(focstim_rpc_RequestDebugStm32DeepSleep, focstim_rpc_RequestDebugStm32DeepSleep, AUTO)


PB_BIND(focstim_rpc_ResponseDebugStm32DeepSleep, focstim_rpc_ResponseDebugStm32DeepSleep, AUTO)


PB_BIND(focstim_rpc_RequestDebugEnterBootloader, focstim_rpc_RequestDebugEnterBootloader, AUTO)



