/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.4.9.1 */

#include "notifications.pb.h"
#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

PB_BIND(focstim_rpc_NotificationBoot, focstim_rpc_NotificationBoot, AUTO)


PB_BIND(focstim_rpc_NotificationDeviceVolume, focstim_rpc_NotificationDeviceVolume, AUTO)


PB_BIND(focstim_rpc_NotificationButtonPress, focstim_rpc_NotificationButtonPress, AUTO)


PB_BIND(focstim_rpc_NotificationCurrents, focstim_rpc_NotificationCurrents, AUTO)


PB_BIND(focstim_rpc_NotificationOutputResistance, focstim_rpc_NotificationOutputResistance, AUTO)


PB_BIND(focstim_rpc_NotificationSkinResistance, focstim_rpc_NotificationSkinResistance, AUTO)


PB_BIND(focstim_rpc_SystemStatsESC1, focstim_rpc_SystemStatsESC1, AUTO)


PB_BIND(focstim_rpc_SystemStatsFocstimV3, focstim_rpc_SystemStatsFocstimV3, AUTO)


PB_BIND(focstim_rpc_NotificationSystemStats, focstim_rpc_NotificationSystemStats, AUTO)


PB_BIND(focstim_rpc_NotificationSignalStats, focstim_rpc_NotificationSignalStats, AUTO)


PB_BIND(focstim_rpc_NotificationBattery, focstim_rpc_NotificationBattery, AUTO)


PB_BIND(focstim_rpc_NotificationLSM6DSOX, focstim_rpc_NotificationLSM6DSOX, AUTO)


PB_BIND(focstim_rpc_NotificationPressure, focstim_rpc_NotificationPressure, AUTO)


PB_BIND(focstim_rpc_NotificationDebugString, focstim_rpc_NotificationDebugString, AUTO)


PB_BIND(focstim_rpc_NotificationDebugAS5311, focstim_rpc_NotificationDebugAS5311, AUTO)


PB_BIND(focstim_rpc_NotificationDebugEdging, focstim_rpc_NotificationDebugEdging, AUTO)


PB_BIND(focstim_rpc_NotificationDebugTeleplot, focstim_rpc_NotificationDebugTeleplot, AUTO)



