/* Automatically generated nanopb header */
/* Generated by nanopb-0.4.9.1 */

#ifndef PB_FOCSTIM_RPC_NOTIFICATIONS_PB_H_INCLUDED
#define PB_FOCSTIM_RPC_NOTIFICATIONS_PB_H_INCLUDED
#include <pb.h>
#include "constants.pb.h"

#if PB_PROTO_HEADER_VERSION != 40
#error Regenerate this file with the current version of nanopb generator.
#endif

/* Struct definitions */
typedef struct _focstim_rpc_NotificationBoot {
    char dummy_field;
} focstim_rpc_NotificationBoot;

typedef struct _focstim_rpc_NotificationDeviceVolume {
    float volume; /* (0, 1) */
    bool locked;
} focstim_rpc_NotificationDeviceVolume;

typedef struct _focstim_rpc_NotificationButtonPress {
    focstim_rpc_ButtonState state;
    uint32_t timestamp_ms; /* millis() on STM32 (uint32_t, wraps ~49.7 days) */
} focstim_rpc_NotificationButtonPress;

typedef struct _focstim_rpc_NotificationCurrents {
    float rms_a; /* body current in amps */
    float rms_b;
    float rms_c;
    float rms_d;
    float peak_a; /* peak body current in amps */
    float peak_b;
    float peak_c;
    float peak_d;
    float output_power; /* output stage power in watts */
    float output_power_skin; /* output stage power in watts, only the component delivered to skin */
    float peak_cmd;
} focstim_rpc_NotificationCurrents;

typedef struct _focstim_rpc_NotificationOutputResistance {
    /* estimated resistance of the entire system, including driver Rdson,
 low-pass filters, and the skin resistance. Generally useful for
 debugging purposes.
 At the current carrier frequency */
    float resistance_a;
    float reluctance_a;
    float resistance_b;
    float reluctance_b;
    float resistance_c;
    float reluctance_c;
    float resistance_d;
    float reluctance_d;
} focstim_rpc_NotificationOutputResistance;

typedef struct _focstim_rpc_NotificationSkinResistance {
    /* best-guess estimate of the skin resistance for display to user.
 At the current carrier frequency.
 Quite inaccurate on V1 due to nonstandard components. */
    float resistance_a;
    float reluctance_a;
    float resistance_b;
    float reluctance_b;
    float resistance_c;
    float reluctance_c;
    float resistance_d;
    float reluctance_d;
} focstim_rpc_NotificationSkinResistance;

typedef struct _focstim_rpc_SystemStatsESC1 {
    float temp_stm32;
    float temp_board;
    float v_bus;
    float v_ref;
} focstim_rpc_SystemStatsESC1;

typedef struct _focstim_rpc_SystemStatsFocstimV3 {
    float temp_stm32;
    float v_sys_min;
    float v_ref;
    float v_boost_min;
    float boost_duty_cycle;
    float v_sys_max;
    float v_boost_max;
} focstim_rpc_SystemStatsFocstimV3;

typedef struct _focstim_rpc_NotificationSystemStats {
    pb_size_t which_system;
    union {
        focstim_rpc_SystemStatsESC1 esc1;
        focstim_rpc_SystemStatsFocstimV3 focstimv3;
    } system;
} focstim_rpc_NotificationSystemStats;

typedef struct _focstim_rpc_NotificationSignalStats {
    float actual_pulse_frequency;
    float v_drive; /* maximum peak-to-peak voltage (low side) */
    float transformer_utilization; /* 0-1 precentage of transformer saturation */
    float voltage_utilization; /* 0-1 percentage of maximum usable voltage */
} focstim_rpc_NotificationSignalStats;

typedef struct _focstim_rpc_NotificationBattery {
    float battery_voltage;
    float battery_charge_rate_watt;
    float battery_soc; /* int? */
    bool wall_power_present;
    float chip_temperature;
} focstim_rpc_NotificationBattery;

typedef struct _focstim_rpc_NotificationLSM6DSOX {
    int32_t acc_x; /* acceleration, conversion factor depends on full scale selection */
    int32_t acc_y;
    int32_t acc_z;
    int32_t gyr_x; /* angular velocity, conversion factor depends on full scale selection */
    int32_t gyr_y;
    int32_t gyr_z;
} focstim_rpc_NotificationLSM6DSOX;

typedef struct _focstim_rpc_NotificationPressure {
    float pressure; /* Pascal */
} focstim_rpc_NotificationPressure;

typedef struct _focstim_rpc_NotificationDebugString {
    char message[200];
} focstim_rpc_NotificationDebugString;

typedef struct _focstim_rpc_NotificationDebugAS5311 {
    int32_t raw;
    int32_t tracked;
    int32_t flags;
} focstim_rpc_NotificationDebugAS5311;

/* only used for debug logging in restim */
typedef struct _focstim_rpc_NotificationDebugEdging {
    float full_power_threshold;
    float reduced_power_threshold;
    float reduction;
} focstim_rpc_NotificationDebugEdging;

typedef struct _focstim_rpc_NotificationDebugTeleplot {
    char id[32];
    float value;
} focstim_rpc_NotificationDebugTeleplot;


#ifdef __cplusplus
extern "C" {
#endif

/* Initializer values for message structs */
#define focstim_rpc_NotificationBoot_init_default {0}
#define focstim_rpc_NotificationDeviceVolume_init_default {0, 0}
#define focstim_rpc_NotificationButtonPress_init_default {_focstim_rpc_ButtonState_MIN, 0}
#define focstim_rpc_NotificationCurrents_init_default {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define focstim_rpc_NotificationOutputResistance_init_default {0, 0, 0, 0, 0, 0, 0, 0}
#define focstim_rpc_NotificationSkinResistance_init_default {0, 0, 0, 0, 0, 0, 0, 0}
#define focstim_rpc_SystemStatsESC1_init_default {0, 0, 0, 0}
#define focstim_rpc_SystemStatsFocstimV3_init_default {0, 0, 0, 0, 0, 0, 0}
#define focstim_rpc_NotificationSystemStats_init_default {0, {focstim_rpc_SystemStatsESC1_init_default}}
#define focstim_rpc_NotificationSignalStats_init_default {0, 0, 0, 0}
#define focstim_rpc_NotificationBattery_init_default {0, 0, 0, 0, 0}
#define focstim_rpc_NotificationLSM6DSOX_init_default {0, 0, 0, 0, 0, 0}
#define focstim_rpc_NotificationPressure_init_default {0}
#define focstim_rpc_NotificationDebugString_init_default {""}
#define focstim_rpc_NotificationDebugAS5311_init_default {0, 0, 0}
#define focstim_rpc_NotificationDebugEdging_init_default {0, 0, 0}
#define focstim_rpc_NotificationDebugTeleplot_init_default {"", 0}
#define focstim_rpc_NotificationBoot_init_zero   {0}
#define focstim_rpc_NotificationDeviceVolume_init_zero {0, 0}
#define focstim_rpc_NotificationButtonPress_init_zero {_focstim_rpc_ButtonState_MIN, 0}
#define focstim_rpc_NotificationCurrents_init_zero {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0}
#define focstim_rpc_NotificationOutputResistance_init_zero {0, 0, 0, 0, 0, 0, 0, 0}
#define focstim_rpc_NotificationSkinResistance_init_zero {0, 0, 0, 0, 0, 0, 0, 0}
#define focstim_rpc_SystemStatsESC1_init_zero    {0, 0, 0, 0}
#define focstim_rpc_SystemStatsFocstimV3_init_zero {0, 0, 0, 0, 0, 0, 0}
#define focstim_rpc_NotificationSystemStats_init_zero {0, {focstim_rpc_SystemStatsESC1_init_zero}}
#define focstim_rpc_NotificationSignalStats_init_zero {0, 0, 0, 0}
#define focstim_rpc_NotificationBattery_init_zero {0, 0, 0, 0, 0}
#define focstim_rpc_NotificationLSM6DSOX_init_zero {0, 0, 0, 0, 0, 0}
#define focstim_rpc_NotificationPressure_init_zero {0}
#define focstim_rpc_NotificationDebugString_init_zero {""}
#define focstim_rpc_NotificationDebugAS5311_init_zero {0, 0, 0}
#define focstim_rpc_NotificationDebugEdging_init_zero {0, 0, 0}
#define focstim_rpc_NotificationDebugTeleplot_init_zero {"", 0}

/* Field tags (for use in manual encoding/decoding) */
#define focstim_rpc_NotificationDeviceVolume_volume_tag 1
#define focstim_rpc_NotificationDeviceVolume_locked_tag 2
#define focstim_rpc_NotificationButtonPress_state_tag 1
#define focstim_rpc_NotificationButtonPress_timestamp_ms_tag 2
#define focstim_rpc_NotificationCurrents_rms_a_tag 1
#define focstim_rpc_NotificationCurrents_rms_b_tag 2
#define focstim_rpc_NotificationCurrents_rms_c_tag 3
#define focstim_rpc_NotificationCurrents_rms_d_tag 4
#define focstim_rpc_NotificationCurrents_peak_a_tag 5
#define focstim_rpc_NotificationCurrents_peak_b_tag 6
#define focstim_rpc_NotificationCurrents_peak_c_tag 7
#define focstim_rpc_NotificationCurrents_peak_d_tag 8
#define focstim_rpc_NotificationCurrents_output_power_tag 9
#define focstim_rpc_NotificationCurrents_output_power_skin_tag 10
#define focstim_rpc_NotificationCurrents_peak_cmd_tag 11
#define focstim_rpc_NotificationOutputResistance_resistance_a_tag 1
#define focstim_rpc_NotificationOutputResistance_reluctance_a_tag 2
#define focstim_rpc_NotificationOutputResistance_resistance_b_tag 3
#define focstim_rpc_NotificationOutputResistance_reluctance_b_tag 4
#define focstim_rpc_NotificationOutputResistance_resistance_c_tag 5
#define focstim_rpc_NotificationOutputResistance_reluctance_c_tag 6
#define focstim_rpc_NotificationOutputResistance_resistance_d_tag 7
#define focstim_rpc_NotificationOutputResistance_reluctance_d_tag 8
#define focstim_rpc_NotificationSkinResistance_resistance_a_tag 1
#define focstim_rpc_NotificationSkinResistance_reluctance_a_tag 2
#define focstim_rpc_NotificationSkinResistance_resistance_b_tag 3
#define focstim_rpc_NotificationSkinResistance_reluctance_b_tag 4
#define focstim_rpc_NotificationSkinResistance_resistance_c_tag 5
#define focstim_rpc_NotificationSkinResistance_reluctance_c_tag 6
#define focstim_rpc_NotificationSkinResistance_resistance_d_tag 7
#define focstim_rpc_NotificationSkinResistance_reluctance_d_tag 8
#define focstim_rpc_SystemStatsESC1_temp_stm32_tag 1
#define focstim_rpc_SystemStatsESC1_temp_board_tag 2
#define focstim_rpc_SystemStatsESC1_v_bus_tag    3
#define focstim_rpc_SystemStatsESC1_v_ref_tag    4
#define focstim_rpc_SystemStatsFocstimV3_temp_stm32_tag 1
#define focstim_rpc_SystemStatsFocstimV3_v_sys_min_tag 2
#define focstim_rpc_SystemStatsFocstimV3_v_ref_tag 3
#define focstim_rpc_SystemStatsFocstimV3_v_boost_min_tag 4
#define focstim_rpc_SystemStatsFocstimV3_boost_duty_cycle_tag 5
#define focstim_rpc_SystemStatsFocstimV3_v_sys_max_tag 6
#define focstim_rpc_SystemStatsFocstimV3_v_boost_max_tag 7
#define focstim_rpc_NotificationSystemStats_esc1_tag 1
#define focstim_rpc_NotificationSystemStats_focstimv3_tag 2
#define focstim_rpc_NotificationSignalStats_actual_pulse_frequency_tag 1
#define focstim_rpc_NotificationSignalStats_v_drive_tag 2
#define focstim_rpc_NotificationSignalStats_transformer_utilization_tag 3
#define focstim_rpc_NotificationSignalStats_voltage_utilization_tag 4
#define focstim_rpc_NotificationBattery_battery_voltage_tag 1
#define focstim_rpc_NotificationBattery_battery_charge_rate_watt_tag 2
#define focstim_rpc_NotificationBattery_battery_soc_tag 3
#define focstim_rpc_NotificationBattery_wall_power_present_tag 4
#define focstim_rpc_NotificationBattery_chip_temperature_tag 5
#define focstim_rpc_NotificationLSM6DSOX_acc_x_tag 1
#define focstim_rpc_NotificationLSM6DSOX_acc_y_tag 2
#define focstim_rpc_NotificationLSM6DSOX_acc_z_tag 3
#define focstim_rpc_NotificationLSM6DSOX_gyr_x_tag 4
#define focstim_rpc_NotificationLSM6DSOX_gyr_y_tag 5
#define focstim_rpc_NotificationLSM6DSOX_gyr_z_tag 6
#define focstim_rpc_NotificationPressure_pressure_tag 1
#define focstim_rpc_NotificationDebugString_message_tag 1
#define focstim_rpc_NotificationDebugAS5311_raw_tag 1
#define focstim_rpc_NotificationDebugAS5311_tracked_tag 2
#define focstim_rpc_NotificationDebugAS5311_flags_tag 3
#define focstim_rpc_NotificationDebugEdging_full_power_threshold_tag 1
#define focstim_rpc_NotificationDebugEdging_reduced_power_threshold_tag 2
#define focstim_rpc_NotificationDebugEdging_reduction_tag 3
#define focstim_rpc_NotificationDebugTeleplot_id_tag 1
#define focstim_rpc_NotificationDebugTeleplot_value_tag 2

/* Struct field encoding specification for nanopb */
#define focstim_rpc_NotificationBoot_FIELDLIST(X, a) \

#define focstim_rpc_NotificationBoot_CALLBACK NULL
#define focstim_rpc_NotificationBoot_DEFAULT NULL

#define focstim_rpc_NotificationDeviceVolume_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    volume,            1) \
X(a, STATIC,   SINGULAR, BOOL,     locked,            2)
#define focstim_rpc_NotificationDeviceVolume_CALLBACK NULL
#define focstim_rpc_NotificationDeviceVolume_DEFAULT NULL

#define focstim_rpc_NotificationButtonPress_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, UENUM,    state,             1) \
X(a, STATIC,   SINGULAR, UINT32,   timestamp_ms,      2)
#define focstim_rpc_NotificationButtonPress_CALLBACK NULL
#define focstim_rpc_NotificationButtonPress_DEFAULT NULL

#define focstim_rpc_NotificationCurrents_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    rms_a,             1) \
X(a, STATIC,   SINGULAR, FLOAT,    rms_b,             2) \
X(a, STATIC,   SINGULAR, FLOAT,    rms_c,             3) \
X(a, STATIC,   SINGULAR, FLOAT,    rms_d,             4) \
X(a, STATIC,   SINGULAR, FLOAT,    peak_a,            5) \
X(a, STATIC,   SINGULAR, FLOAT,    peak_b,            6) \
X(a, STATIC,   SINGULAR, FLOAT,    peak_c,            7) \
X(a, STATIC,   SINGULAR, FLOAT,    peak_d,            8) \
X(a, STATIC,   SINGULAR, FLOAT,    output_power,      9) \
X(a, STATIC,   SINGULAR, FLOAT,    output_power_skin,  10) \
X(a, STATIC,   SINGULAR, FLOAT,    peak_cmd,         11)
#define focstim_rpc_NotificationCurrents_CALLBACK NULL
#define focstim_rpc_NotificationCurrents_DEFAULT NULL

#define focstim_rpc_NotificationOutputResistance_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    resistance_a,      1) \
X(a, STATIC,   SINGULAR, FLOAT,    reluctance_a,      2) \
X(a, STATIC,   SINGULAR, FLOAT,    resistance_b,      3) \
X(a, STATIC,   SINGULAR, FLOAT,    reluctance_b,      4) \
X(a, STATIC,   SINGULAR, FLOAT,    resistance_c,      5) \
X(a, STATIC,   SINGULAR, FLOAT,    reluctance_c,      6) \
X(a, STATIC,   SINGULAR, FLOAT,    resistance_d,      7) \
X(a, STATIC,   SINGULAR, FLOAT,    reluctance_d,      8)
#define focstim_rpc_NotificationOutputResistance_CALLBACK NULL
#define focstim_rpc_NotificationOutputResistance_DEFAULT NULL

#define focstim_rpc_NotificationSkinResistance_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    resistance_a,      1) \
X(a, STATIC,   SINGULAR, FLOAT,    reluctance_a,      2) \
X(a, STATIC,   SINGULAR, FLOAT,    resistance_b,      3) \
X(a, STATIC,   SINGULAR, FLOAT,    reluctance_b,      4) \
X(a, STATIC,   SINGULAR, FLOAT,    resistance_c,      5) \
X(a, STATIC,   SINGULAR, FLOAT,    reluctance_c,      6) \
X(a, STATIC,   SINGULAR, FLOAT,    resistance_d,      7) \
X(a, STATIC,   SINGULAR, FLOAT,    reluctance_d,      8)
#define focstim_rpc_NotificationSkinResistance_CALLBACK NULL
#define focstim_rpc_NotificationSkinResistance_DEFAULT NULL

#define focstim_rpc_SystemStatsESC1_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    temp_stm32,        1) \
X(a, STATIC,   SINGULAR, FLOAT,    temp_board,        2) \
X(a, STATIC,   SINGULAR, FLOAT,    v_bus,             3) \
X(a, STATIC,   SINGULAR, FLOAT,    v_ref,             4)
#define focstim_rpc_SystemStatsESC1_CALLBACK NULL
#define focstim_rpc_SystemStatsESC1_DEFAULT NULL

#define focstim_rpc_SystemStatsFocstimV3_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    temp_stm32,        1) \
X(a, STATIC,   SINGULAR, FLOAT,    v_sys_min,         2) \
X(a, STATIC,   SINGULAR, FLOAT,    v_ref,             3) \
X(a, STATIC,   SINGULAR, FLOAT,    v_boost_min,       4) \
X(a, STATIC,   SINGULAR, FLOAT,    boost_duty_cycle,   5) \
X(a, STATIC,   SINGULAR, FLOAT,    v_sys_max,         6) \
X(a, STATIC,   SINGULAR, FLOAT,    v_boost_max,       7)
#define focstim_rpc_SystemStatsFocstimV3_CALLBACK NULL
#define focstim_rpc_SystemStatsFocstimV3_DEFAULT NULL

#define focstim_rpc_NotificationSystemStats_FIELDLIST(X, a) \
X(a, STATIC,   ONEOF,    MESSAGE,  (system,esc1,system.esc1),   1) \
X(a, STATIC,   ONEOF,    MESSAGE,  (system,focstimv3,system.focstimv3),   2)
#define focstim_rpc_NotificationSystemStats_CALLBACK NULL
#define focstim_rpc_NotificationSystemStats_DEFAULT NULL
#define focstim_rpc_NotificationSystemStats_system_esc1_MSGTYPE focstim_rpc_SystemStatsESC1
#define focstim_rpc_NotificationSystemStats_system_focstimv3_MSGTYPE focstim_rpc_SystemStatsFocstimV3

#define focstim_rpc_NotificationSignalStats_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    actual_pulse_frequency,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    v_drive,           2) \
X(a, STATIC,   SINGULAR, FLOAT,    transformer_utilization,   3) \
X(a, STATIC,   SINGULAR, FLOAT,    voltage_utilization,   4)
#define focstim_rpc_NotificationSignalStats_CALLBACK NULL
#define focstim_rpc_NotificationSignalStats_DEFAULT NULL

#define focstim_rpc_NotificationBattery_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    battery_voltage,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    battery_charge_rate_watt,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    battery_soc,       3) \
X(a, STATIC,   SINGULAR, BOOL,     wall_power_present,   4) \
X(a, STATIC,   SINGULAR, FLOAT,    chip_temperature,   5)
#define focstim_rpc_NotificationBattery_CALLBACK NULL
#define focstim_rpc_NotificationBattery_DEFAULT NULL

#define focstim_rpc_NotificationLSM6DSOX_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, SINT32,   acc_x,             1) \
X(a, STATIC,   SINGULAR, SINT32,   acc_y,             2) \
X(a, STATIC,   SINGULAR, SINT32,   acc_z,             3) \
X(a, STATIC,   SINGULAR, SINT32,   gyr_x,             4) \
X(a, STATIC,   SINGULAR, SINT32,   gyr_y,             5) \
X(a, STATIC,   SINGULAR, SINT32,   gyr_z,             6)
#define focstim_rpc_NotificationLSM6DSOX_CALLBACK NULL
#define focstim_rpc_NotificationLSM6DSOX_DEFAULT NULL

#define focstim_rpc_NotificationPressure_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    pressure,          1)
#define focstim_rpc_NotificationPressure_CALLBACK NULL
#define focstim_rpc_NotificationPressure_DEFAULT NULL

#define focstim_rpc_NotificationDebugString_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   message,           1)
#define focstim_rpc_NotificationDebugString_CALLBACK NULL
#define focstim_rpc_NotificationDebugString_DEFAULT NULL

#define focstim_rpc_NotificationDebugAS5311_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, INT32,    raw,               1) \
X(a, STATIC,   SINGULAR, SINT32,   tracked,           2) \
X(a, STATIC,   SINGULAR, INT32,    flags,             3)
#define focstim_rpc_NotificationDebugAS5311_CALLBACK NULL
#define focstim_rpc_NotificationDebugAS5311_DEFAULT NULL

#define focstim_rpc_NotificationDebugEdging_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, FLOAT,    full_power_threshold,   1) \
X(a, STATIC,   SINGULAR, FLOAT,    reduced_power_threshold,   2) \
X(a, STATIC,   SINGULAR, FLOAT,    reduction,         3)
#define focstim_rpc_NotificationDebugEdging_CALLBACK NULL
#define focstim_rpc_NotificationDebugEdging_DEFAULT NULL

#define focstim_rpc_NotificationDebugTeleplot_FIELDLIST(X, a) \
X(a, STATIC,   SINGULAR, STRING,   id,                1) \
X(a, STATIC,   SINGULAR, FLOAT,    value,             2)
#define focstim_rpc_NotificationDebugTeleplot_CALLBACK NULL
#define focstim_rpc_NotificationDebugTeleplot_DEFAULT NULL

extern const pb_msgdesc_t focstim_rpc_NotificationBoot_msg;
extern const pb_msgdesc_t focstim_rpc_NotificationDeviceVolume_msg;
extern const pb_msgdesc_t focstim_rpc_NotificationButtonPress_msg;
extern const pb_msgdesc_t focstim_rpc_NotificationCurrents_msg;
extern const pb_msgdesc_t focstim_rpc_NotificationOutputResistance_msg;
extern const pb_msgdesc_t focstim_rpc_NotificationSkinResistance_msg;
extern const pb_msgdesc_t focstim_rpc_SystemStatsESC1_msg;
extern const pb_msgdesc_t focstim_rpc_SystemStatsFocstimV3_msg;
extern const pb_msgdesc_t focstim_rpc_NotificationSystemStats_msg;
extern const pb_msgdesc_t focstim_rpc_NotificationSignalStats_msg;
extern const pb_msgdesc_t focstim_rpc_NotificationBattery_msg;
extern const pb_msgdesc_t focstim_rpc_NotificationLSM6DSOX_msg;
extern const pb_msgdesc_t focstim_rpc_NotificationPressure_msg;
extern const pb_msgdesc_t focstim_rpc_NotificationDebugString_msg;
extern const pb_msgdesc_t focstim_rpc_NotificationDebugAS5311_msg;
extern const pb_msgdesc_t focstim_rpc_NotificationDebugEdging_msg;
extern const pb_msgdesc_t focstim_rpc_NotificationDebugTeleplot_msg;

/* Defines for backwards compatibility with code written before nanopb-0.4.0 */
#define focstim_rpc_NotificationBoot_fields &focstim_rpc_NotificationBoot_msg
#define focstim_rpc_NotificationDeviceVolume_fields &focstim_rpc_NotificationDeviceVolume_msg
#define focstim_rpc_NotificationButtonPress_fields &focstim_rpc_NotificationButtonPress_msg
#define focstim_rpc_NotificationCurrents_fields &focstim_rpc_NotificationCurrents_msg
#define focstim_rpc_NotificationOutputResistance_fields &focstim_rpc_NotificationOutputResistance_msg
#define focstim_rpc_NotificationSkinResistance_fields &focstim_rpc_NotificationSkinResistance_msg
#define focstim_rpc_SystemStatsESC1_fields &focstim_rpc_SystemStatsESC1_msg
#define focstim_rpc_SystemStatsFocstimV3_fields &focstim_rpc_SystemStatsFocstimV3_msg
#define focstim_rpc_NotificationSystemStats_fields &focstim_rpc_NotificationSystemStats_msg
#define focstim_rpc_NotificationSignalStats_fields &focstim_rpc_NotificationSignalStats_msg
#define focstim_rpc_NotificationBattery_fields &focstim_rpc_NotificationBattery_msg
#define focstim_rpc_NotificationLSM6DSOX_fields &focstim_rpc_NotificationLSM6DSOX_msg
#define focstim_rpc_NotificationPressure_fields &focstim_rpc_NotificationPressure_msg
#define focstim_rpc_NotificationDebugString_fields &focstim_rpc_NotificationDebugString_msg
#define focstim_rpc_NotificationDebugAS5311_fields &focstim_rpc_NotificationDebugAS5311_msg
#define focstim_rpc_NotificationDebugEdging_fields &focstim_rpc_NotificationDebugEdging_msg
#define focstim_rpc_NotificationDebugTeleplot_fields &focstim_rpc_NotificationDebugTeleplot_msg

/* Maximum encoded size of messages (where known) */
#define FOCSTIM_RPC_NOTIFICATIONS_PB_H_MAX_SIZE  focstim_rpc_NotificationDebugString_size
#define focstim_rpc_NotificationBattery_size     22
#define focstim_rpc_NotificationBoot_size        0
#define focstim_rpc_NotificationButtonPress_size 8
#define focstim_rpc_NotificationCurrents_size    55
#define focstim_rpc_NotificationDebugAS5311_size 28
#define focstim_rpc_NotificationDebugEdging_size 15
#define focstim_rpc_NotificationDebugString_size 202
#define focstim_rpc_NotificationDebugTeleplot_size 38
#define focstim_rpc_NotificationDeviceVolume_size 7
#define focstim_rpc_NotificationLSM6DSOX_size    36
#define focstim_rpc_NotificationOutputResistance_size 40
#define focstim_rpc_NotificationPressure_size    5
#define focstim_rpc_NotificationSignalStats_size 20
#define focstim_rpc_NotificationSkinResistance_size 40
#define focstim_rpc_NotificationSystemStats_size 37
#define focstim_rpc_SystemStatsESC1_size         20
#define focstim_rpc_SystemStatsFocstimV3_size    35

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif
